import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import {ThemeProvider} from "../components/theme-provider";
import "./globals.css";

import Nav from "../components/Nav";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${playfair.variable} h-full antialiased`}
   suppressHydrationWarning>
      <body className="min-h-full flex flex-col">
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Nav />
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
